Travis CI: drop Go 1.9, add Go 1.13
Go 1.9 fails to build the fs tests:

  # github.com/kylelemons/godebug/diff
  ../../kylelemons/godebug/diff/diff.go:50:13: undefined: strings.Builder
  ?   	github.com/hanwen/go-fuse/example/zipfs	[no test files]
  FAIL	github.com/hanwen/go-fuse/fs [build failed]

So drop Go 1.9.

Add Go 1.13, which is already at 1.13.3.

Change-Id: Id2286cddc3973a1388f94e1b294db36d7663c37b