.github: set user_allow_other in /etc/fuse.conf
Fixes this test failure:

2023/04/13 20:25:20 callFusermount: executing ["/usr/bin/fusermount3" "/tmp/TestDirectMount4166040800" "-o" "allow_other,subtype=/tmp/go-build1065896,max_read=131072"]
/usr/bin/fusermount3: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf

\--- FAIL: TestDirectMount (0.01s)
    mount_linux_test.go:117: fusermount exited with code 256

Change-Id: I4a2a2983dd422de9360b17068ac0d8a3947d453d