Update patch set 3
Patch Set 3: Verified+1 Code-Review+2

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > I think this is not enough to fix https://github.com/hanwen/go-fuse/issues/55 .
> > On the plus side, the test catches the problem:
> > 
> > ~/go/src/github.com/hanwen/go-fuse/fs$ go test
> > --- FAIL: TestPosix (0.20s)
> >     --- FAIL: TestPosix/RenameOpenDir (0.00s)
> >         test.go:389: got ino e50bb, want e50ba
> > FAIL
> > exit status 1
> > FAIL	github.com/hanwen/go-fuse/v2/fs	0.962s
> 
> I saw the test pass, but it was before I added the inode check.

done. I was checking the wrong inodes against each other 

the kernel doesn't pass in the file handle even if we do fstat, so we can't do much better than we do here.

Patch-set: 3
Reviewer: Gerrit User 1007980 <1007980@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=+2
Label: Verified=+1